### ISSUE TITLE
Firebase URL is invalid

### ISSUE THREAD

**Issue by freddyheppell** [youngrewired/yrs-chat#2]
On page load, Console shows `Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com`.

This may be because index.js loads config.js, but only config.default.js exists. Thus, `***firebase-url***` is loaded as the url

**Comment by Mitame** [comment]
It part of my merge (#1).. if you copy the config.default.json to config.json, then edit it for your stuff, it works fine (unless that's changed since).

**Comment by brks** [comment]
Config.js does exist, but Node doesn't like it. @MrMindImplosion @freddinator

**Comment by brks** [comment]
@freddinator @MrMindImplosion So, the Node stuff is parsing the config, and it's in the file, so I don't actually know. :+1:

**Comment by freddyheppell** [comment]
Hopefully this should be fixed. If not, reopen.

**Comment by brks** [comment]
Everything works now.
